# Site
name: OpusTheRobot
description: Web developer & youtuber
meta_description: Web developer & youtuber
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'limo@allianceofdroids.org.au'
google_analytics:
disqus: xjekyll
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a1a46b37b0f3600122c23bc&product=sticky-share-buttons"></script>'

# Authors
authors:
  john:
    name: Liam
    display_name:  Liam Arbuckle
    image: /assets/images/john.jpg
    email: opus@allianceofdroids.org.au
    web: acord.tech/opus
    twitter: OpusTheRobot
    description: Hi, I'm a youtuber and a developer.

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: OpusTheRobot
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: John Doe
links:
    - https://twitter.com/OpusTheRobot
    - https://www.facebook.com/droidology
    - https://www.linkedin.com/
    - https://github.com/irisdroidology
